---

spring:
  profiles: cloud

info:
  description: message to all cw portal apps

eureka:
  client:
    fetch-registry: false
    serviceUrl:
      defaultZone: ${vcap.services.cw-portal-service-registry.credentials.uri}/eureka/

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000
