---

spring:
  profiles: cloud

info:
  description: message to all cw portal apps

eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.cw-portal-service-registry.credentials.uri}/eureka
